NOT_KILLED_BY_OWN_BOMB = "NOT_KILLED_BY_OWN_BOMB"
UNALLOWED_BOMB = "UNALLOWED_BOMB"

DISTANCE_FROM_BOMB_INCREASED = "DISTANCE_FROM_BOMB_INCREASED"
DISTANCE_FROM_BOMB_DECREASED = "DISTANCE_FROM_BOMB_DECREASED"
DISTANCE_TO_COIN_INCREASED = "DISTANCE_TO_COIN_INCREASED"
DISTANCE_TO_COIN_DECREASED = "DISTANCE_TO_COIN_DECREASED"

APPROACHED_ENEMY = "APPROACHED_ENEMY"
DISAPPROACHED_ENEMY = "DISAPPROACHED_ENEMY"

LEFT_POTENTIAL_EXPLOSION_ZONE = "LEFT_POTENTIAL_EXPLOSION_ZONE"
ENTERED_POTENTIAL_EXPLOSION_ZONE = "ENTERED_POTENTIAL_EXPLOSION_ZONE"

IN_SAFE_ZONE = "IN_SAFE_ZONE"
AGENT_CORNERED = "AGENT_CORNERED"