NOT_KILLED_BY_OWN_BOMB = "NOT_KILLED_BY_OWN_BOMB"
UNALLOWED_BOMB = "UNALLOWED_BOMB"

DISTANCE_FROM_BOMB_INCREASED = "DISTANCE_FROM_BOMB_INCREASED"
DISTANCE_FROM_BOMB_DECREASED = "DISTANCE_FROM_BOMB_DECREASED"
DISTANCE_TO_COIN_INCREASED = "DISTANCE_TO_COIN_INCREASED"
MOVED_TOWARDS_COIN = "MOVED_TOWARDS_COIN"
MOVED_AWAY_FROM_COIN = "MOVED_AWAY_FROM_COIN"

APPROACHED_ENEMY = "APPROACHED_ENEMY"
DISAPPROACHED_ENEMY = "DISAPPROACHED_ENEMY"

LEFT_POTENTIAL_EXPLOSION_ZONE = "LEFT_POTENTIAL_EXPLOSION_ZONE"
ENTERED_POTENTIAL_EXPLOSION_ZONE = "ENTERED_POTENTIAL_EXPLOSION_ZONE"

IN_SAFE_ZONE = "IN_SAFE_ZONE"
AGENT_CORNERED = "AGENT_CORNERED"

CRATE_IN_EXPLOSION_ZONE = "CRATE_IN_EXPLOSION_ZONE"

SCORE_REWARD = "SCORE_REWARD"
PLACEMENT_REWARD = "PLACEMENT_REWARD"

PATH_SHORTENED_TO_OBJECTIVE = "PATH_SHORTENED_TO_OBJECTIVE"

ATTACKED_ENEMY = "ATTACKED_ENEMY"

MOVED_TOWARDS_END_OF_EXPLOSION = "MOVED_TOWARDS_END_OF_EXPLOSION"

GUARANTEED_SUICIDE = "GUARANTEED_SUICIDE"

STAYED_IN_EXPLOSION_RADIUS = "STAYED_IN_EXPLOSION_RADIUS"
STAYED_OUTSIDE_ACTIVE_EXPLOSION = "STAYED_OUTSIDE_ACTIVE_EXPLOSION"
ENTERED_ACTIVE_EXPLOSION = "ENTERED_ACTIVE_EXPLOSION"