NOT_KILLED_BY_OWN_BOMB = "NOT_KILLED_BY_OWN_BOMB"
UNALLOWED_BOMB = "UNALLOWED_BOMB"

MOVED_TOWARDS_COIN = "MOVED_TOWARDS_COIN"
MOVED_AWAY_FROM_COIN = "MOVED_AWAY_FROM_COIN"

LEFT_POTENTIAL_EXPLOSION_ZONE = "LEFT_POTENTIAL_EXPLOSION_ZONE"
ENTERED_POTENTIAL_EXPLOSION_ZONE = "ENTERED_POTENTIAL_EXPLOSION_ZONE"

CRATE_IN_EXPLOSION_ZONE = "CRATE_IN_EXPLOSION_ZONE"

ATTACKED_ENEMY = "ATTACKED_ENEMY"

MOVED_TOWARDS_END_OF_EXPLOSION = "MOVED_TOWARDS_END_OF_EXPLOSION"

GUARANTEED_SUICIDE = "GUARANTEED_SUICIDE"

STAYED_IN_EXPLOSION_RADIUS = "STAYED_IN_EXPLOSION_RADIUS"
